-- Allow subscriptions to follow an SCS account regardless of email or LINE login.
-- Run once in the Supabase SQL editor before deploying the updated worker.js.

begin;

alter table public.user_plans
  add column if not exists subscription_id bigint generated by default as identity,
  add column if not exists account_id text,
  add column if not exists display_name text,
  add column if not exists auth_provider text not null default 'email';

-- Older SCS databases use email as the primary key. LINE accounts may not
-- have an email, so move the primary key to a neutral identity column first.
do $$
declare
  primary_key_name text;
  primary_key_uses_email boolean;
begin
  select constraint_name,
         exists (
           select 1
           from information_schema.key_column_usage key_column
           where key_column.table_schema = 'public'
             and key_column.table_name = 'user_plans'
             and key_column.constraint_name = table_constraint.constraint_name
             and key_column.column_name = 'email'
         )
  into primary_key_name, primary_key_uses_email
  from information_schema.table_constraints table_constraint
  where table_constraint.table_schema = 'public'
    and table_constraint.table_name = 'user_plans'
    and table_constraint.constraint_type = 'PRIMARY KEY'
  limit 1;

  if primary_key_name is not null and primary_key_uses_email then
    execute format('alter table public.user_plans drop constraint %I', primary_key_name);
  end if;

  if not exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'user_plans'
      and constraint_type = 'PRIMARY KEY'
  ) then
    alter table public.user_plans
      add constraint user_plans_pkey primary key (subscription_id);
  end if;
end $$;

alter table public.user_plans alter column email drop not null;

create unique index if not exists user_plans_email_unique
  on public.user_plans (email)
  where email is not null;

-- Preserve all existing email subscriptions and attach them to their SCS account.
update public.user_plans as plan
set account_id = account.id::text,
    display_name = coalesce(plan.display_name, account.nickname),
    auth_provider = coalesce(account.auth_provider, 'email')
from public.user_accounts as account
where plan.account_id is null
  and plan.email is not null
  and account.email is not null
  and lower(plan.email) = lower(account.email);

create unique index if not exists user_plans_account_id_unique
  on public.user_plans (account_id);

alter table public.purchase_requests
  add column if not exists account_id text,
  add column if not exists display_name text,
  add column if not exists auth_provider text not null default 'email';

alter table public.purchase_requests alter column email drop not null;

update public.purchase_requests as request
set account_id = account.id::text,
    display_name = coalesce(request.display_name, account.nickname),
    auth_provider = coalesce(account.auth_provider, 'email')
from public.user_accounts as account
where request.account_id is null
  and request.email is not null
  and account.email is not null
  and lower(request.email) = lower(account.email);

create index if not exists purchase_requests_account_id_idx
  on public.purchase_requests (account_id);

commit;
